/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2022-05-12 17:43:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.almaviva.sie.web.util.WebApplicationConstants;

public final class listaReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/jsp/include/messaggioErrore.jsp", Long.valueOf(1529422286000L));
    _jspx_dependants.put("/jsp/include/header.jsp", Long.valueOf(1529422286000L));
    _jspx_dependants.put("/WEB-INF/display-tag.tld", Long.valueOf(1529422286000L));
    _jspx_dependants.put("/jsp/include/footer.jsp", Long.valueOf(1529422286000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fselect_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fhidden_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005finput_0026_005fsize_005freadonly_005fpath_005fcssClass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fselect_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fhidden_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005finput_0026_005fsize_005freadonly_005fpath_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005ff_005fselect_0026_005fpath.release();
    _005fjspx_005ftagPool_005ff_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.release();
    _005fjspx_005ftagPool_005ff_005fhidden_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005ff_005finput_0026_005fsize_005freadonly_005fpath_005fcssClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"now\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n");
      out.write("<title>SIE - Sistema Informativo Entrate</title>\r\n");
      out.write("<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/displaytag-table.css\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table class=\"w100 bgcolor\" cellpadding=\"0\" cellspacing=\"0\">\t\r\n");
      out.write("\r\n");
      out.write("<tr>\t\r\n");
      out.write("\t\t\t<td  width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t\t<table class=\"w100 bgcolor\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td class=\"width:196;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo_sie.jpg\"  />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"w100\">\t\r\n");
      out.write("\t\t<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t<tbody><tr>\t\t\t<td>\r\n");
      out.write("\t\t<table width=\"100%\">\t\t\t\r\n");
      out.write("<tbody><tr>\r\n");
      out.write("<td class=\"w80 alignTop\" align=\"center\">\r\n");
      out.write("&nbsp;\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /jsp/include/header.jsp(43,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mstrConnectionParam.provenienza ne null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<td class=\"w20 mnulat\" align=\"center\">\r\n");
            out.write("\r\n");
            out.write("<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mstrConnectionParam.provenienza}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" class=\"somm\"><img src=\"");
            out.print(request.getContextPath());
            out.write("/img/torna_sie.png\"  /></a> \r\n");
            out.write("\r\n");
            out.write("</td>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t<tr>\t<td class=\"intestazione\">\t\t\t\t\t\r\n");
      out.write("<img src=\"../images/sie/spazio.gif\" alt=\"\" height=\"2\" width=\"1\"></td>\t</tr>\t\r\n");
      out.write("<tr>\t<td class=\"intestazione\">\t\t\t\t\t\r\n");
      out.write("<img src=\"../images/sie/spazio.gif\" alt=\"\" height=\"2\" width=\"1\">\t<br></td>\t</tr>\r\n");
      out.write("<tr>\t\t<td>\t\t\t\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"titolo\" align=\"right\">\r\n");
      out.write("&nbsp;&nbsp;");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /jsp/include/header.jsp(61,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mstrConnectionParam.provenienza eq null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<a href=\"");
            out.print(request.getContextPath());
            out.write("/jsp/welcomePage.jsp\">Home</a> |\r\n");
            out.write("\t\t\t\t\t\t<a href=\"");
            out.print(request.getContextPath());
            out.write("/logout.jsp\">Uscita </a>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("</td></tr></tbody></table></td>\t\r\n");
      out.write("</tr>\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td></tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t<td><br>Utente connesso:<br> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utente.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td><td class=\"intestazione2\"><br><i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${funzione.nomeFunzione}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</i></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      //  f:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_f_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_f_005fform_005f0_reused = false;
      try {
        _jspx_th_f_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_f_005fform_005f0.setParent(null);
        // /jsp/listaReport.jsp(3,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_f_005fform_005f0.setAction(request.getContextPath() + WebApplicationConstants.VIEW_DETT_REPORT);
        // /jsp/listaReport.jsp(3,0) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_f_005fform_005f0.setModelAttribute("stampeForm");
        // /jsp/listaReport.jsp(3,0) name = method type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
        _jspx_th_f_005fform_005f0.setMethod("post");
        int[] _jspx_push_body_count_f_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_f_005fform_005f0 = _jspx_th_f_005fform_005f0.doStartTag();
          if (_jspx_eval_f_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t<table class=\"w100\">\r\n");
              out.write("\t<tr>\r\n");
              out.write("\t<td><br>Le stampe contrassegnate con (Rs) sono Report Services</td>\r\n");
              out.write("\t</tr>\r\n");
              out.write("\t\t<tr>\r\n");
              out.write("\t\t\t<td>");
              if (_jspx_meth_c_005fif_005f2(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t<table class=\"w100 riepilogo\">\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w25\"><strong>Codice:</strong>\r\n");
              out.write("\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profilo.codi_pk_profilo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w25\"><strong>Livello organizzativo:</strong>\r\n");
              out.write("\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profilo.codi_livello_org}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w25\"><strong>Provincia:</strong>\r\n");
              out.write("\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profilo.codi_ragioneria}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t</table></td>\r\n");
              out.write("\r\n");
              out.write("\t\t</tr>\r\n");
              out.write("\t\t<tr>\r\n");
              out.write("\t\t\t<td><br>\r\n");
              out.write("\t\t\t\t<table class=\"w100 cornice\">\r\n");
              out.write("\t\t\t\t");
              if (_jspx_meth_c_005fif_005f3(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td colspan=\"2\"><strong>Selezione Stampe</strong></td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w15 nowrap\">Percorso</td>\r\n");
              out.write("\t\t\t\t\t\t<td>");
              if (_jspx_meth_f_005fselect_005f0(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
                return;
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"Stampe abilitate\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"puls\" name=\"metodo\"/> <input type=\"submit\" value=\"Stampe personali\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"puls\" name=\"metodo\"/></td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w15 nowrap\">Descrizione</td>\r\n");
              out.write("\t\t\t\t\t\t<td>");
              if (_jspx_meth_f_005fhidden_005f0(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_f_005finput_005f0(_jspx_th_f_005fform_005f0, _jspx_page_context, _jspx_push_body_count_f_005fform_005f0))
                return;
              out.write(" <input type=\"submit\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"buttoncerca\" name=\"metodo\" value=\"...\"></td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t</table>\r\n");
              out.write("\t\t\t</td>\r\n");
              out.write("\t\t</tr>\r\n");
              out.write("\t\t<tr>\r\n");
              out.write("\t\t\t<td>\r\n");
              out.write("\t\t\t\t<table class=\"w100\">\r\n");
              out.write("\t\t\t\t\t<tr>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<td class=\"w87\"><input type=\"submit\" value=\"Avanti\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"puls\" name=\"metodo\"/> <input type=\"submit\" value=\"Indietro\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"puls\" name=\"metodo\" /></td>\r\n");
              out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" value=\"Pulisci\"\r\n");
              out.write("\t\t\t\t\t\t\tclass=\"puls\" name=\"metodo\"/></td>\r\n");
              out.write("\t\t\t\t\t</tr>\r\n");
              out.write("\t\t\t\t</table> <br />\r\n");
              out.write("\t\t\t</td>\r\n");
              out.write("\t\t</tr>\r\n");
              out.write("\t\t");
              out.write("<tr>\r\n");
              out.write("\t<td colspan=\"2\" class=\"mnulat alignCenter\">\r\n");
              out.write("\t\t<table class=\"alignCenter\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
              out.write("\t\t\t<tr>\r\n");
              out.write("\t\t\t\t<td class=\"alignCenter\">Sistema Informativo della Ragioneria\r\n");
              out.write("\t\t\t\t\tGenerale dello Stato</td>\r\n");
              out.write("\t\t\t\t<td><img src=\"");
              out.print(request.getContextPath());
              out.write("/img/logo_rep.gif\"\r\n");
              out.write("\t\t\t\t\talt=\"\" style=\"\" /></td>\r\n");
              out.write("\t\t\t</tr>\r\n");
              out.write("\t\t</table>\r\n");
              out.write("\t</td>\r\n");
              out.write("\r\n");
              out.write("</tr>\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t</table>\r\n");
              int evalDoAfterBody = _jspx_th_f_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_f_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_f_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_f_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_f_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005ff_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_f_005fform_005f0);
        _jspx_th_f_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_f_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
      // /jsp/include/messaggioErrore.jsp(1,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errore ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<li class=\"error\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errore}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
      // /jsp/listaReport.jsp(32,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ok ne null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
          out.write("\t\t\t<strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ok}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</strong>\r\n");
          out.write("\t\t\t</td></tr>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_f_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005ff_005fselect_0026_005fpath.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    boolean _jspx_th_f_005fselect_005f0_reused = false;
    try {
      _jspx_th_f_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
      // /jsp/listaReport.jsp(44,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005fselect_005f0.setPath("path");
      int[] _jspx_push_body_count_f_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_f_005fselect_005f0 = _jspx_th_f_005fselect_005f0.doStartTag();
        if (_jspx_eval_f_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            if (_jspx_meth_f_005foptions_005f0(_jspx_th_f_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_f_005fselect_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_f_005fselect_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_f_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_f_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_f_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_f_005fselect_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ff_005fselect_0026_005fpath.reuse(_jspx_th_f_005fselect_005f0);
      _jspx_th_f_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_f_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_f_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005ff_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_f_005foptions_005f0_reused = false;
    try {
      _jspx_th_f_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fselect_005f0);
      // /jsp/listaReport.jsp(45,8) name = items type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stampeForm.listaStampe}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /jsp/listaReport.jsp(45,8) name = itemValue type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005foptions_005f0.setItemValue("value");
      // /jsp/listaReport.jsp(45,8) name = itemLabel type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005foptions_005f0.setItemLabel("label");
      int[] _jspx_push_body_count_f_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_f_005foptions_005f0 = _jspx_th_f_005foptions_005f0.doStartTag();
        if (_jspx_th_f_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_f_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_f_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_f_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ff_005foptions_0026_005fitems_005fitemValue_005fitemLabel_005fnobody.reuse(_jspx_th_f_005foptions_005f0);
      _jspx_th_f_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_f_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:hidden
    org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_f_005fhidden_005f0 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005ff_005fhidden_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
    boolean _jspx_th_f_005fhidden_005f0_reused = false;
    try {
      _jspx_th_f_005fhidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
      // /jsp/listaReport.jsp(54,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005fhidden_005f0.setPath("codiStampa");
      int[] _jspx_push_body_count_f_005fhidden_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_f_005fhidden_005f0 = _jspx_th_f_005fhidden_005f0.doStartTag();
        if (_jspx_th_f_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_f_005fhidden_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_f_005fhidden_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_f_005fhidden_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ff_005fhidden_0026_005fpath_005fnobody.reuse(_jspx_th_f_005fhidden_005f0);
      _jspx_th_f_005fhidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_f_005fhidden_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_f_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_f_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ff_005finput_0026_005fsize_005freadonly_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_f_005finput_005f0_reused = false;
    try {
      _jspx_th_f_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fform_005f0);
      // /jsp/listaReport.jsp(55,6) name = path type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005finput_005f0.setPath("descStampa");
      // /jsp/listaReport.jsp(55,6) name = size type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005finput_005f0.setSize("42");
      // /jsp/listaReport.jsp(55,6) name = readonly type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005finput_005f0.setReadonly(true);
      // /jsp/listaReport.jsp(55,6) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_f_005finput_005f0.setCssClass("descrizione");
      int[] _jspx_push_body_count_f_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_f_005finput_005f0 = _jspx_th_f_005finput_005f0.doStartTag();
        if (_jspx_th_f_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_f_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_f_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_f_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ff_005finput_0026_005fsize_005freadonly_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_f_005finput_005f0);
      _jspx_th_f_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_f_005finput_005f0_reused);
    }
    return false;
  }
}
